import Head from "next/head";
import Image from "next/image";
import {
  useColorMode,
  Box,
  Stack,
  useColorModeValue,
  useMediaQuery,
} from "@chakra-ui/react";

import CTAtext from "../src/components/CTAtext";
import Form from "../src/components/Form";
import Layout from "../src/components/Layout";
import TodoIcon from "../src/components/TodoIcon";
import AffiliationsIcon from "../src/components/AffiliationsIcon";

export default function Home() {
  return (
    <Stack minWidth="90vw" minHeight="100vh">
      <Head>
        <title>Plotly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <Stack width="100%">
        <Layout>
          <Box>
            <Stack
              display="flex"
              direction={{ base: "column", sm: "column", xl: "row" }}
              position="relative"
            >
              <CTAtext />
              <Form />
            </Stack>
            <Stack
              display="flex"
              direction={{ base: "column", sm: "column", xl: "row" }}
              position="relative"
              zIndex={"-2"}
              top={{
                base: "-3rem",
                sm: "-3rem",
                md: "-5rem",
                xl: "-4.5rem",
                "2xl": "-10rem",
              }}
            >
              <TodoIcon />
              <AffiliationsIcon />
            </Stack>
          </Box>
        </Layout>
      </Stack>
    </Stack>
  );
}
