import Head from 'next/head';
import { Box, Stack } from '@chakra-ui/react';

import CTAtext from '../src/components/CTAtext';
import Form from '../src/components/Form';
import Layout from '../src/components/Layout';
import TodoIcon from '../src/components/TodoIcon';
import AffiliationsIcon from '../src/components/AffiliationsIcon';

export default function Home() {
  return (
    <Stack minWidth="90vw" minHeight="100vh">
      <Head>
        <title>Plotly</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://media-exp1.licdn.com/dms/image/C4E0BAQEOgbmAxw6CXQ/company-logo_100_100/0/1637276238787?e=1671062400&v=beta&t=lROE_jWpydlXaq-Zuf6P_Q7-3NsXeQ0COaU3d2WShKQ"
        />
      </Head>

      <Stack width="100%">
        <Layout>
          <Box>
            <Stack
              display="flex"
              direction={{ base: 'column', sm: 'column', xl: 'row' }}
              position="relative"
            >
              <CTAtext />
              <Form />
            </Stack>
            <Stack
              display="flex"
              direction={{ base: 'column', sm: 'column', xl: 'row' }}
              position="relative"
              zIndex={'-2'}
              top={{
                base: '-3rem',
                sm: '-3rem',
                md: '-5rem',
                xl: '-4.5rem',
                '2xl': '-10rem',
              }}
            >
              <TodoIcon />
              <AffiliationsIcon />
            </Stack>
          </Box>
        </Layout>
      </Stack>
    </Stack>
  );
}
